[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_program = "8VppkDTytWadXok7JAPVeipZnCMtf4HqwXMHkw41oLJu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mindf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"